jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

spring:
    application:
        name: sist_contable
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
          connection-timeout: 30000
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update